import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

function Login() {
  const navigate = useNavigate()
  const [modal, setModal] = useState(null)
  const [step, setStep] = useState(1)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [email, setEmail] = useState('')
  const [loginForm, setLoginForm] = useState({ email: '', password: '' })
  const [registerForm, setRegisterForm] = useState({
    name: '', email: '', password: '', age: '', weight: '', height: '', diet_type: '', goal: ''
  })
  const [visible, setVisible] = useState(false)

  useEffect(() => {
    setTimeout(() => setVisible(true), 100)
  }, [])

  const updateLogin = (e) => setLoginForm({ ...loginForm, [e.target.name]: e.target.value })
  const updateRegister = (e) => setRegisterForm({ ...registerForm, [e.target.name]: e.target.value })

  const handleLogin = async () => {
    if (!loginForm.email || !loginForm.password) { setError('Please fill all fields!'); return }
    setLoading(true); setError('')
    try {
      const res = await fetch('https://nutriai-backend-xspo.onrender.com/api/login', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(loginForm)
      })
      const data = await res.json()
      if (res.ok) {
        localStorage.setItem('token', data.token)
        localStorage.setItem('user', JSON.stringify(data.user))
        navigate('/dashboard')
      } else { setError(data.error || 'Login failed!') }
    } catch { setError('Cannot connect to server!') }
    setLoading(false)
  }

  const handleRegister = async () => {
    if (!registerForm.diet_type || !registerForm.goal) { setError('Please select diet type and goal!'); return }
    setLoading(true); setError('')
    try {
      const res = await fetch('https://nutriai-backend-xspo.onrender.com/api/register', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...registerForm, age: parseInt(registerForm.age), weight: parseFloat(registerForm.weight), height: parseFloat(registerForm.height) })
      })
      const data = await res.json()
      if (res.ok) {
        localStorage.setItem('token', data.token)
        localStorage.setItem('user', JSON.stringify(data.user))
        navigate('/dashboard')
      } else { setError(data.error || 'Registration failed!') }
    } catch { setError('Cannot connect to server!') }
    setLoading(false)
  }

  const features = [
    { icon: '🧠', title: 'AI Meal Planning', desc: 'Personalized meal plans generated by advanced AI based on your health profile and Indian food preferences.', color: 'from-violet-500 to-purple-600', light: 'bg-violet-50', tag: 'AI Powered' },
    { icon: '⚖️', title: 'BMI Calculator', desc: 'Real-time BMI tracking with personalized health insights and recommendations for your body type.', color: 'from-blue-500 to-cyan-600', light: 'bg-blue-50', tag: 'Smart Tracking' },
    { icon: '🔥', title: 'Calorie Tracker', desc: 'Track daily calories, macros, and micronutrients with our comprehensive Indian food database.', color: 'from-orange-500 to-red-500', light: 'bg-orange-50', tag: 'Real-time' },
    { icon: '💡', title: 'Smart Recommendations', desc: 'Get AI-powered nutrition recommendations based on your activity level, goals, and health data.', color: 'from-yellow-500 to-amber-600', light: 'bg-yellow-50', tag: 'Personalized' },
    { icon: '📈', title: 'Progress Tracking', desc: 'Visualize your health journey with beautiful charts, streaks, and milestone celebrations.', color: 'from-green-500 to-emerald-600', light: 'bg-green-50', tag: 'Analytics' },
    { icon: '🎯', title: 'Goal-Based Diet Plans', desc: 'Whether its weight loss, muscle gain or staying fit — get a customized plan that works for you.', color: 'from-pink-500 to-rose-600', light: 'bg-pink-50', tag: 'Goal Driven' },
  ]

  const testimonials = [
    { name: 'Priya Sharma', role: 'Software Engineer, Bangalore', avatar: '👩‍💻', text: 'NutriAI completely transformed my eating habits! Lost 8kg in 3 months following the personalized Indian meal plans. The AI consultation is incredibly accurate!', rating: 5, result: '-8 kg in 3 months' },
    { name: 'Rahul Verma', role: 'Fitness Enthusiast, Mumbai', avatar: '🏋️‍♂️', text: 'Best diet app for Indians! It actually understands our food culture and suggests dal, roti, sabzi in the right proportions. Gained 5kg of muscle!', rating: 5, result: '+5 kg muscle gain' },
    { name: 'Anita Patel', role: 'Doctor, Ahmedabad', avatar: '👩‍⚕️', text: 'As a doctor, I recommend NutriAI to my patients. The calorie tracking is accurate and the AI gives evidence-based nutrition advice. Impressive technology!', rating: 5, result: '95% accuracy' },
  ]

  const stats = [
    { value: '10K+', label: 'Active Users', icon: '👥' },
    { value: '95%', label: 'Satisfaction Rate', icon: '⭐' },
    { value: '50K+', label: 'Meal Plans Generated', icon: '🍽️' },
    { value: '100%', label: 'Free Forever', icon: '🎁' },
  ]

  const footerLinks = {
    'Quick Links': ['Home', 'About', 'Features', 'Pricing', 'Contact'],
    'Services': ['Diet Plan Generator', 'BMI Calculator', 'Calorie Counter', 'Nutrition Tips', 'Weight Loss Plans'],
    'Legal': ['Privacy Policy', 'Terms & Conditions', 'Cookie Policy', 'GDPR Compliance'],
    'Support': ['FAQ', 'Help Center', 'Email Support', 'Community Forum'],
  }

  return (
    <div className="min-h-screen bg-white overflow-x-hidden">

      {/* ── NAVBAR ── */}
      <nav className="fixed top-0 w-full z-50 glass border-b border-white/50 shadow-sm">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center shadow-lg shadow-green-200 animate-float">
              <span className="text-xl">🥗</span>
            </div>
            <div>
              <span className="text-xl font-bold text-gray-900" style={{fontFamily:'Syne, sans-serif'}}>NutriAI</span>
              <span className="ml-2 text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded-full font-semibold">BETA</span>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-8">
            {['Features', 'How it Works', 'Testimonials', 'Pricing'].map((item) => (
              <a key={item} href={`#${item.toLowerCase().replace(' ', '-')}`}
                className="text-sm font-medium text-gray-500 hover:text-green-600 transition-colors duration-200 relative group">
                {item}
                <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-green-500 group-hover:w-full transition-all duration-300"></span>
              </a>
            ))}
          </div>

          <div className="flex items-center gap-3">
            <button onClick={() => { setModal('login'); setError('') }}
              className="text-sm font-semibold text-gray-600 hover:text-green-600 px-4 py-2 rounded-xl hover:bg-green-50 transition-all duration-200">
              Sign In
            </button>
            <button onClick={() => { setModal('register'); setStep(1); setError('') }}
              className="btn-primary px-5 py-2.5 rounded-xl text-sm font-bold shadow-lg shadow-green-200">
              Get Started Free →
            </button>
          </div>
        </div>
      </nav>

      {/* ── HERO ── */}
      <section className="relative min-h-screen flex items-center pt-20 overflow-hidden">
        {/* Background */}
        <div className="absolute inset-0 bg-gradient-to-br from-green-50 via-white to-emerald-50"></div>
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-gradient-to-bl from-green-200/40 to-transparent rounded-full -translate-y-1/2 translate-x-1/4"></div>
        <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-gradient-to-tr from-emerald-200/30 to-transparent rounded-full translate-y-1/2 -translate-x-1/4"></div>

        {/* Floating decorations */}
        <div className="absolute top-32 right-32 w-4 h-4 bg-green-400 rounded-full animate-float opacity-60"></div>
        <div className="absolute top-56 right-64 w-3 h-3 bg-emerald-300 rounded-full animate-float delay-300 opacity-60"></div>
        <div className="absolute bottom-40 left-32 w-5 h-5 bg-teal-400 rounded-full animate-float delay-500 opacity-40"></div>

        <div className="max-w-7xl mx-auto px-6 grid md:grid-cols-2 gap-16 items-center relative z-10 py-20">

          {/* Left */}
          <div className={`transition-all duration-1000 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
            <div className="inline-flex items-center gap-2 bg-green-100 text-green-700 px-4 py-2 rounded-full text-sm font-bold mb-8 border border-green-200 shadow-sm">
              <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
              AI-Powered Nutrition Platform
              <span className="bg-green-500 text-white text-xs px-2 py-0.5 rounded-full">NEW</span>
            </div>

            <h1 className="text-5xl md:text-6xl font-extrabold text-gray-900 leading-[1.1] mb-6" style={{fontFamily:'Syne, sans-serif'}}>
              Your Personal<br />
              <span className="shimmer-text">AI Diet</span><br />
              Consultant
            </h1>

            <p className="text-lg text-gray-500 mb-8 leading-relaxed max-w-lg">
              Smart meal plans, calorie tracking, and personalized nutrition powered by AI. Built specifically for Indian lifestyle and food culture.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 mb-10">
              <button onClick={() => { setModal('register'); setStep(1); setError('') }}
                className="btn-primary px-8 py-4 rounded-2xl text-base font-bold shadow-xl shadow-green-200 flex items-center justify-center gap-2">
                🚀 Get Started Free
              </button>
              <button onClick={() => document.getElementById('how-it-works')?.scrollIntoView({ behavior: 'smooth' })}
                className="px-8 py-4 rounded-2xl text-base font-bold border-2 border-gray-200 text-gray-600 hover:border-green-400 hover:text-green-600 hover:bg-green-50 transition-all duration-300 flex items-center justify-center gap-2">
                🥗 Generate Diet Plan
              </button>
            </div>

            {/* Trust badges */}
            <div className="flex flex-wrap gap-3">
              {['✅ No credit card', '✅ Free forever', '✅ Indian food database', '✅ AI-powered'].map((b, i) => (
                <span key={i} className="text-sm text-gray-500 font-medium">{b}</span>
              ))}
            </div>
          </div>

          {/* Right — Illustration */}
          <div className={`transition-all duration-1000 delay-300 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
            <div className="relative">
              {/* Main Card */}
              <div className="bg-white rounded-3xl shadow-2xl p-6 border border-gray-100 animate-float">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center">
                    <span className="text-xl">🤖</span>
                  </div>
                  <div>
                    <p className="font-bold text-gray-800 text-sm">NutriAI Assistant</p>
                    <p className="text-xs text-green-500 font-medium flex items-center gap-1">
                      <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse"></span> Online
                    </p>
                  </div>
                </div>
                <div className="bg-gray-50 rounded-2xl p-4 mb-3">
                  <p className="text-sm text-gray-600">Namaste! 🙏 Based on your profile, I recommend:</p>
                  <div className="mt-2 space-y-2">
                    {['🌅 Breakfast: Oats + Banana (320 kcal)', '☀️ Lunch: Dal Rice + Salad (580 kcal)', '🌙 Dinner: Khichdi + Dahi (400 kcal)'].map((m, i) => (
                      <div key={i} className="flex items-center gap-2 text-xs text-gray-700 bg-white rounded-xl p-2">
                        <span>{m}</span>
                      </div>
                    ))}
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-2">
                  {[{ label: 'Calories', value: '1,300', color: 'text-orange-500' }, { label: 'Protein', value: '68g', color: 'text-blue-500' }, { label: 'BMI', value: '22.4', color: 'text-green-500' }].map((m, i) => (
                    <div key={i} className="bg-gray-50 rounded-xl p-2 text-center">
                      <p className={`text-base font-bold ${m.color}`}>{m.value}</p>
                      <p className="text-xs text-gray-400">{m.label}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Floating badges */}
              <div className="absolute -top-4 -right-4 bg-white rounded-2xl shadow-lg p-3 flex items-center gap-2 border border-gray-100">
                <span className="text-2xl">⭐</span>
                <div>
                  <p className="text-xs font-bold text-gray-800">4.9/5 Rating</p>
                  <p className="text-xs text-gray-400">10K+ users</p>
                </div>
              </div>

              <div className="absolute -bottom-4 -left-4 bg-gradient-to-r from-green-500 to-emerald-600 rounded-2xl shadow-lg p-3 text-white">
                <p className="text-xs font-bold">🎯 Goal Achieved!</p>
                <p className="text-xs opacity-80">Lost 5kg this month</p>
              </div>
            </div>
          </div>
        </div>

        {/* Stats Bar */}
        <div className="absolute bottom-0 left-0 right-0 bg-white/80 backdrop-blur-xl border-t border-gray-100 py-6">
          <div className="max-w-7xl mx-auto px-6">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              {stats.map((s, i) => (
                <div key={i} className="flex items-center gap-3">
                  <span className="text-2xl">{s.icon}</span>
                  <div>
                    <p className="text-xl font-extrabold text-gray-900" style={{fontFamily:'Syne, sans-serif'}}>{s.value}</p>
                    <p className="text-xs text-gray-400 font-medium">{s.label}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section id="features" className="py-28 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <span className="text-sm font-bold text-green-600 uppercase tracking-widest bg-green-50 px-4 py-2 rounded-full border border-green-100">Features</span>
            <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4" style={{fontFamily:'Syne, sans-serif'}}>
              Powerful AI-Driven Features
            </h2>
            <p className="text-gray-400 text-lg max-w-2xl mx-auto">Everything you need to transform your nutrition habits with cutting-edge artificial intelligence</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div key={i} className="card-hover group p-8 rounded-3xl border border-gray-100 bg-white cursor-pointer">
                <div className={`w-14 h-14 ${f.light} rounded-2xl flex items-center justify-center text-3xl mb-5 group-hover:scale-110 transition-transform duration-300`}>
                  {f.icon}
                </div>
                <div className="flex items-center gap-2 mb-3">
                  <h3 className="text-lg font-bold text-gray-800 group-hover:text-green-600 transition-colors" style={{fontFamily:'Syne, sans-serif'}}>{f.title}</h3>
                  <span className={`text-xs bg-gradient-to-r ${f.color} text-white px-2 py-0.5 rounded-full font-semibold`}>{f.tag}</span>
                </div>
                <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
                <div className="mt-4 flex items-center gap-1 text-green-600 text-sm font-bold opacity-0 group-hover:opacity-100 transition-all duration-300 translate-x-0 group-hover:translate-x-1">
                  Learn more →
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section id="how-it-works" className="py-28 bg-gradient-to-br from-gray-50 to-green-50/30">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <span className="text-sm font-bold text-green-600 uppercase tracking-widest bg-green-50 px-4 py-2 rounded-full border border-green-100">How It Works</span>
            <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4" style={{fontFamily:'Syne, sans-serif'}}>
              Start in 3 Simple Steps
            </h2>
            <p className="text-gray-400 text-lg">Get your personalized AI diet plan in under 2 minutes</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
            <div className="hidden md:block absolute top-16 left-1/4 right-1/4 h-0.5 bg-gradient-to-r from-green-200 via-emerald-300 to-green-200"></div>

            {[
              { num: '01', icon: '👤', title: 'Create Your Profile', desc: 'Sign up in 30 seconds. Tell us about your age, weight, height, and health goals.', points: ['Personal health data', 'Dietary preferences', 'Health goals'] },
              { num: '02', icon: '🤖', title: 'Get AI Diet Plan', desc: 'Our AI instantly creates a personalized Indian diet plan tailored just for you.', points: ['7-day meal plans', 'Indian food options', 'Macro targets'] },
              { num: '03', icon: '📈', title: 'Track & Improve', desc: 'Chat with AI, track meals, and watch your health transform every single day.', points: ['AI chat consultation', 'Progress tracking', 'Health insights'] },
            ].map((s, i) => (
              <div key={i} className="card-hover bg-white rounded-3xl p-8 border border-gray-100 relative">
                <div className="absolute -top-4 left-8 w-8 h-8 bg-gradient-to-br from-green-500 to-emerald-600 rounded-xl flex items-center justify-center text-white text-xs font-extrabold shadow-lg shadow-green-200">
                  {s.num}
                </div>
                <div className="text-4xl mb-4 mt-2">{s.icon}</div>
                <h3 className="text-xl font-bold text-gray-800 mb-3" style={{fontFamily:'Syne, sans-serif'}}>{s.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed mb-4">{s.desc}</p>
                <ul className="space-y-2">
                  {s.points.map((p, j) => (
                    <li key={j} className="flex items-center gap-2 text-sm text-gray-500">
                      <span className="w-5 h-5 bg-green-100 text-green-600 rounded-full flex items-center justify-center text-xs flex-shrink-0">✓</span>
                      {p}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TESTIMONIALS ── */}
      <section id="testimonials" className="py-28 bg-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center mb-16">
            <span className="text-sm font-bold text-green-600 uppercase tracking-widest bg-green-50 px-4 py-2 rounded-full border border-green-100">Testimonials</span>
            <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 mt-4 mb-4" style={{fontFamily:'Syne, sans-serif'}}>
              Real Results, Real People
            </h2>
            <p className="text-gray-400 text-lg">Join thousands of Indians transforming their health with NutriAI</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <div key={i} className="card-hover p-8 rounded-3xl border border-gray-100 bg-white">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex gap-1">
                    {[...Array(t.rating)].map((_, j) => <span key={j} className="text-yellow-400">⭐</span>)}
                  </div>
                  <span className="text-xs bg-green-100 text-green-700 px-3 py-1 rounded-full font-bold">{t.result}</span>
                </div>
                <p className="text-gray-500 text-sm leading-relaxed mb-6 italic">"{t.text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-green-100 to-emerald-100 rounded-full flex items-center justify-center text-xl">
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-bold text-gray-800 text-sm">{t.name}</p>
                    <p className="text-xs text-gray-400">{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── WHY CHOOSE US ── */}
      <section className="py-28 bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-10 left-10 w-64 h-64 bg-green-500 rounded-full filter blur-3xl"></div>
          <div className="absolute bottom-10 right-10 w-64 h-64 bg-emerald-500 rounded-full filter blur-3xl"></div>
        </div>

        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="text-center mb-16">
            <span className="text-sm font-bold text-green-400 uppercase tracking-widest bg-green-900/50 px-4 py-2 rounded-full border border-green-800">Why Choose Us</span>
            <h2 className="text-4xl md:text-5xl font-extrabold mt-4 mb-4" style={{fontFamily:'Syne, sans-serif'}}>
              Why <span className="text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-emerald-400">NutriAI</span> is Different
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
            {[
              { icon: '🇮🇳', title: 'Built for India', desc: 'The only AI diet platform that truly understands Indian cuisine, festivals, and food culture.' },
              { icon: '🧬', title: 'Science-Based', desc: 'All recommendations are based on peer-reviewed nutritional science and clinical guidelines.' },
              { icon: '🔒', title: 'Privacy First', desc: 'Your health data is encrypted and never shared with third parties. 100% secure.' },
              { icon: '⚡', title: 'Instant Results', desc: 'Get your personalized diet plan in under 60 seconds. No waiting, no appointments.' },
            ].map((b, i) => (
              <div key={i} className="glass-dark rounded-3xl p-6 hover:border-green-500/50 border border-white/10 transition-all duration-300 hover:-translate-y-1">
                <div className="text-4xl mb-4">{b.icon}</div>
                <h3 className="text-lg font-bold mb-2" style={{fontFamily:'Syne, sans-serif'}}>{b.title}</h3>
                <p className="text-gray-400 text-sm leading-relaxed">{b.desc}</p>
              </div>
            ))}
          </div>

          {/* CTA */}
          <div className="text-center">
            <div className="inline-block bg-gradient-to-r from-green-500 via-emerald-500 to-teal-500 p-0.5 rounded-3xl shadow-2xl shadow-green-900/50">
              <div className="bg-gray-900 rounded-3xl px-12 py-10">
                <h3 className="text-3xl font-extrabold mb-3" style={{fontFamily:'Syne, sans-serif'}}>Ready to Transform Your Health?</h3>
                <p className="text-gray-400 mb-6">Join 10,000+ Indians already achieving their health goals</p>
                <button onClick={() => { setModal('register'); setStep(1); setError('') }}
                  className="btn-primary px-10 py-4 rounded-2xl text-lg font-bold shadow-xl shadow-green-900/50 inline-flex items-center gap-2">
                  🚀 Start Free Today
                </button>
                <p className="text-gray-500 text-sm mt-4">No credit card • Free forever • Cancel anytime</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="bg-gray-950 text-gray-400 pt-20 pb-8">
        <div className="max-w-7xl mx-auto px-6">

          {/* Newsletter */}
          <div className="bg-gradient-to-r from-green-500/10 to-emerald-500/10 border border-green-500/20 rounded-3xl p-8 mb-16 flex flex-col md:flex-row items-center justify-between gap-6">
            <div>
              <h3 className="text-white text-xl font-bold mb-1" style={{fontFamily:'Syne, sans-serif'}}>Get Nutrition Tips in Your Inbox</h3>
              <p className="text-gray-400 text-sm">Weekly AI-powered nutrition insights, recipes, and health tips</p>
            </div>
            <div className="flex gap-3 w-full md:w-auto">
              <input type="email" value={email} onChange={e => setEmail(e.target.value)}
                placeholder="Enter your email..."
                className="flex-1 md:w-72 bg-gray-800 border border-gray-700 text-white rounded-xl px-4 py-3 text-sm focus:outline-none focus:border-green-500 transition-colors" />
              <button className="btn-primary px-6 py-3 rounded-xl text-sm font-bold whitespace-nowrap">
                Subscribe →
              </button>
            </div>
          </div>

          {/* Links */}
          <div className="grid grid-cols-2 md:grid-cols-6 gap-8 mb-12">
            <div className="col-span-2">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center">
                  <span className="text-xl">🥗</span>
                </div>
                <span className="text-xl font-bold text-white" style={{fontFamily:'Syne, sans-serif'}}>NutriAI</span>
              </div>
              <p className="text-sm leading-relaxed mb-6 text-gray-500">
                AI-powered nutrition consultation platform built for the Indian lifestyle. Transform your health with science-backed personalized diet plans.
              </p>
              {/* Social icons */}
              <div className="flex gap-3">
                {['𝕏', 'in', 'f', '📷'].map((s, i) => (
                  <a key={i} href="#"
                    className="w-9 h-9 bg-gray-800 hover:bg-green-600 rounded-xl flex items-center justify-center text-sm font-bold transition-all duration-300 hover:scale-110">
                    {s}
                  </a>
                ))}
              </div>
            </div>

            {Object.entries(footerLinks).map(([title, links]) => (
              <div key={title}>
                <h4 className="text-white font-bold mb-4 text-sm uppercase tracking-widest" style={{fontFamily:'Syne, sans-serif'}}>{title}</h4>
                <ul className="space-y-3">
                  {links.map((link, i) => (
                    <li key={i}>
                      <a href="#" className="text-sm hover:text-green-400 transition-colors duration-200 flex items-center gap-1 group">
                        <span className="w-0 group-hover:w-2 overflow-hidden transition-all duration-200 text-green-500">›</span>
                        {link}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* Bottom */}
          <div className="border-t border-gray-800 pt-8 flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-sm text-gray-500">© 2025 NutriAI. All rights reserved. Built with ❤️ by <span className="text-green-400 font-semibold">Adarsh Thakur</span></p>
            <div className="flex gap-4 flex-wrap justify-center">
              {['React 18', 'Python Flask', 'SQLite', 'Groq AI', 'Vercel'].map((t, i) => (
                <span key={i} className="text-xs bg-gray-800 text-gray-400 px-3 py-1 rounded-full border border-gray-700">{t}</span>
              ))}
            </div>
          </div>
        </div>
      </footer>

      {/* ── MODAL ── */}
      {modal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-md z-50 flex items-center justify-center p-4"
          onClick={(e) => e.target === e.currentTarget && setModal(null)}>
          <div className="bg-white rounded-3xl shadow-2xl w-full max-w-md overflow-hidden" style={{animation:'fadeInUp 0.3s ease-out'}}>

            <div className="bg-gradient-to-r from-green-500 via-emerald-500 to-teal-500 p-6 text-white relative overflow-hidden">
              <div className="absolute -top-6 -right-6 w-24 h-24 bg-white/10 rounded-full"></div>
              <div className="absolute -bottom-4 -left-4 w-16 h-16 bg-white/10 rounded-full"></div>
              <button onClick={() => setModal(null)}
                className="absolute top-4 right-4 w-8 h-8 bg-white/20 hover:bg-white/30 rounded-xl flex items-center justify-center text-white transition-all">✕</button>
              <div className="text-3xl mb-2">🥗</div>
              <h2 className="text-xl font-bold" style={{fontFamily:'Syne, sans-serif'}}>
                {modal === 'login' ? 'Welcome Back!' : 'Create Free Account'}
              </h2>
              <p className="text-green-100 text-sm">{modal === 'login' ? 'Sign in to NutriAI' : `Step ${step} of 3 — Let's get started`}</p>
              {modal === 'register' && (
                <div className="mt-3 bg-white/20 rounded-full h-1.5">
                  <div className="bg-white rounded-full h-1.5 transition-all duration-700"
                    style={{ width: step === 1 ? '33%' : step === 2 ? '66%' : '100%' }}></div>
                </div>
              )}
            </div>

            <div className="p-6">
              {error && (
                <div className="bg-red-50 border border-red-200 text-red-600 text-sm px-4 py-3 rounded-xl mb-4 flex items-center gap-2">
                  ⚠️ {error}
                </div>
              )}

              {modal === 'login' && (
                <div>
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Email Address</label>
                  <input name="email" value={loginForm.email} onChange={updateLogin} placeholder="adarsh@email.com" type="email"
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-4 focus:outline-none focus:border-green-400 focus:shadow-lg focus:shadow-green-100 bg-gray-50 focus:bg-white transition-all text-gray-700" />
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Password</label>
                  <input name="password" value={loginForm.password} onChange={updateLogin} placeholder="••••••••" type="password"
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-6 focus:outline-none focus:border-green-400 focus:shadow-lg focus:shadow-green-100 bg-gray-50 focus:bg-white transition-all text-gray-700" />
                  <button onClick={handleLogin} disabled={loading}
                    className="w-full btn-primary py-4 rounded-2xl font-bold text-base disabled:opacity-50">
                    {loading ? '⏳ Signing in...' : 'Sign In →'}
                  </button>
                  <p className="text-center text-gray-400 text-sm mt-4">
                    New to NutriAI?{' '}
                    <button onClick={() => { setModal('register'); setStep(1); setError('') }} className="text-green-500 font-bold hover:text-green-700">Create free account</button>
                  </p>
                </div>
              )}

              {modal === 'register' && step === 1 && (
                <div>
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Full Name</label>
                  <input name="name" value={registerForm.name} onChange={updateRegister} placeholder="Adarsh Thakur"
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-3 focus:outline-none focus:border-green-400 bg-gray-50 focus:bg-white transition-all text-gray-700" />
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Email Address</label>
                  <input name="email" value={registerForm.email} onChange={updateRegister} placeholder="adarsh@email.com" type="email"
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-3 focus:outline-none focus:border-green-400 bg-gray-50 focus:bg-white transition-all text-gray-700" />
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">Password</label>
                  <input name="password" value={registerForm.password} onChange={updateRegister} placeholder="Min 8 characters" type="password"
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-5 focus:outline-none focus:border-green-400 bg-gray-50 focus:bg-white transition-all text-gray-700" />
                  <button onClick={() => { if (!registerForm.name || !registerForm.email || !registerForm.password) { setError('Please fill all fields!'); return } setError(''); setStep(2) }}
                    className="w-full btn-primary py-4 rounded-2xl font-bold text-base">
                    Continue →
                  </button>
                  <p className="text-center text-gray-400 text-sm mt-4">
                    Already have an account?{' '}
                    <button onClick={() => { setModal('login'); setError('') }} className="text-green-500 font-bold">Sign in</button>
                  </p>
                </div>
              )}

              {modal === 'register' && step === 2 && (
                <div>
                  <p className="text-gray-400 text-sm mb-4">Help us personalize your diet plan</p>
                  <div className="grid grid-cols-3 gap-3 mb-5">
                    {[{ label: '🎂 Age', name: 'age', placeholder: '19', unit: 'yrs' }, { label: '⚖️ Weight', name: 'weight', placeholder: '58', unit: 'kg' }, { label: '📏 Height', name: 'height', placeholder: '165', unit: 'cm' }].map(f => (
                      <div key={f.name}>
                        <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">{f.label}</label>
                        <input name={f.name} value={registerForm[f.name]} onChange={updateRegister} placeholder={f.placeholder} type="number"
                          className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 focus:outline-none focus:border-green-400 bg-gray-50 focus:bg-white transition-all text-gray-700 text-center font-bold" />
                      </div>
                    ))}
                  </div>
                  <button onClick={() => { if (!registerForm.age || !registerForm.weight || !registerForm.height) { setError('Please fill all fields!'); return } setError(''); setStep(3) }}
                    className="w-full btn-primary py-4 rounded-2xl font-bold text-base">
                    Continue →
                  </button>
                  <button onClick={() => setStep(1)} className="w-full text-gray-400 text-sm mt-3 hover:text-green-500 transition-colors">← Back</button>
                </div>
              )}

              {modal === 'register' && step === 3 && (
                <div>
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">🥦 Diet Preference</label>
                  <select name="diet_type" value={registerForm.diet_type} onChange={updateRegister}
                    className="w-full border-2 border-gray-100 rounded-xl p-3 mt-1 mb-4 focus:outline-none focus:border-green-400 bg-gray-50 focus:bg-white transition-all text-gray-700">
                    <option value="">Select your diet type</option>
                    <option value="Vegetarian">🥗 Vegetarian</option>
                    <option value="Non-Vegetarian">🍗 Non-Vegetarian</option>
                    <option value="Vegan">🌱 Vegan</option>
                    <option value="Keto">🥑 Keto</option>
                  </select>
                  <label className="text-xs font-bold text-gray-400 uppercase tracking-widest">🏆 Primary Goal</label>
                  <div className="grid grid-cols-3 gap-2 mt-2 mb-5">
                    {[{ label: 'Lose Weight', icon: '⚖️' }, { label: 'Build Muscle', icon: '💪' }, { label: 'Stay Fit', icon: '🏃' }].map(g => (
                      <button key={g.label} onClick={() => setRegisterForm({ ...registerForm, goal: g.label })}
                        className={`p-3 rounded-2xl border-2 text-xs font-bold transition-all duration-300 flex flex-col items-center gap-1 hover:scale-105 active:scale-95
                          ${registerForm.goal === g.label ? 'border-green-500 bg-green-50 text-green-700 shadow-lg shadow-green-100' : 'border-gray-100 text-gray-500 bg-gray-50 hover:border-green-200'}`}>
                        <span className="text-xl">{g.icon}</span>
                        {g.label}
                      </button>
                    ))}
                  </div>
                  <button onClick={handleRegister} disabled={loading}
                    className="w-full btn-primary py-4 rounded-2xl font-bold text-base disabled:opacity-50">
                    {loading ? '⏳ Creating account...' : '🚀 Get Started Free'}
                  </button>
                  <button onClick={() => setStep(2)} className="w-full text-gray-400 text-sm mt-3 hover:text-green-500 transition-colors">← Back</button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default Login